import type { Metadata } from "next";
import "./globals.css";
import { SidebarWrapper } from "@/components/sidebar-wrapper";

export const metadata: Metadata = {
    title: "p2p exemplo",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body className={`antialiased`}>
                <SidebarWrapper>
                    {children}
                </SidebarWrapper>
            </body>
        </html>
    );
}
